#!/bin/bash

set -e

cd $(dirname "$0")
sudo ./install-build-dependencies
make -f libusb.mk
sudo ./local-stow dist/libusb*
make -f yaml-cpp.mk
sudo ./local-stow dist/yaml-cpp*
make -f libftdi.mk
sudo ./local-stow dist/libftdi*
make -f libpinproc.mk
sudo ./local-stow dist/libpinproc*
make -f pypinproc.mk
sudo ./local-stow dist/pypinproc*
